version: '1'
services:
  auth_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Wscbs_G9
      MYSQL_DATABASE: auth
    volumes:
      - auth_mysql:/var/lib/mysql

  auth:
    build: authentication/.
    restart: on-failure:10
    ports:
      - "60000:60000"
    environment:
      MYSQL_HOST: auth_db
      MYSQL_USER: root
      MYSQL_PASSWORD: Wscbs_G9
      MYSQL_DB: auth
      SECRET_KEY: /run/secrets/auth_key
    secrets:
      - auth_key
    depends_on:
      auth_db:
        condition: service_started

  gateway:
    build: gateway/.
    ports:
      - "8080:8080"
    environment:
      AUTH_IP: "auth:60000"
      URL_SHORTENER_IP: "url_shortener:53333"

  url_shortener_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Wscbs_G9
      MYSQL_DATABASE: url_shortener
    volumes:
      - url_shortener_mysql:/var/lib/mysql

  id_gen:
    build: id_generation/.
    restart: on-failure:10
    ports:
      - "55555:55555"
    environment:
      MYSQL_HOST: url_shortener_db
      MYSQL_USER: root
      MYSQL_PASSWORD: Wscbs_G9
      MYSQL_DB: url_shortener
    depends_on:
      url_shortener_db:
        condition: service_started

  url_shortener:
    build: url_shortener/.
    restart: on-failure:10
    ports:
      - "53333:53333"
    environment:
      MYSQL_HOST: url_shortener_db
      MYSQL_USER: root
      MYSQL_PASSWORD: Wscbs_G9
      MYSQL_DB: url_shortener
      AUTH_IP: "auth:60000"
      IDGEN_IP: "id_gen:55555"
    depends_on:
      url_shortener_db:
        condition: service_started
      id_gen:
        condition: service_started
volumes:
  url_shortener_mysql:
  auth_mysql:
secrets:
  auth_key:
    file: auth_key.txt