apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-gateway
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  defaultBackend:
    service:
      name: url-shortener-svc
      port:
        number: 80  
  rules:
    - host: www.example.com
      http:
        paths:
          - path: /auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-svc
                port:
                  name: http
          - path: /urls(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: url-shortener-svc
                port:
                  name: http

