apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: url-shortener-svc
  labels:
    app: url-shortener-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 53333
    nodePort: 30081
  selector:
    app: url-shortener
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
  labels:
    app: url-shortener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: url-shortener
        image: 555isfaiz/wscbs_g9_urlshortener
        ports:
        - containerPort: 53333
        env:
        - name: MYSQL_HOST
          value: mysql-urlshortener-svc
        - name: MYSQL_PASSWORD
          value: WscbsG9ur1Sh0rt3ner
        - name: MYSQL_DB
          value: url-shortener
        - name: AUTH_IP
          value: auth-svc
        - name: IDGEN_IP
          value: id-gen-svc

